// flow-typed signature: 14696372b5f69d41d90ac39c19dac5ae
// flow-typed version: <<STUB>>/@uifabric/icons_v^5.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uifabric/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uifabric/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uifabric/icons/lib-amd/fabric-icons-0' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-1' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-10' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-11' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-12' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-13' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-14' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-2' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-3' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-4' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-5' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-6' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-7' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-8' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons-9' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/fabric-icons' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/icon-aliases' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/IconNames' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-amd/index' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-0' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-1' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-10' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-11' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-12' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-13' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-14' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-2' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-3' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-4' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-5' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-6' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-7' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-8' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons-9' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/fabric-icons' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/icon-aliases' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/IconNames' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib-es2015/index' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-0' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-1' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-10' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-11' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-12' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-13' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-14' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-2' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-3' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-4' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-5' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-6' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-7' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-8' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons-9' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/fabric-icons' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/icon-aliases' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/IconNames' {
  declare module.exports: any;
}

declare module '@uifabric/icons/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uifabric/icons/lib-amd/fabric-icons-0.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-0'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-1.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-1'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-10.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-10'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-11.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-11'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-12.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-12'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-13.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-13'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-14.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-14'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-2.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-2'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-3.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-3'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-4.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-4'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-5.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-5'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-6.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-6'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-7.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-7'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-8.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-8'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons-9.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons-9'>;
}
declare module '@uifabric/icons/lib-amd/fabric-icons.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/fabric-icons'>;
}
declare module '@uifabric/icons/lib-amd/icon-aliases.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/icon-aliases'>;
}
declare module '@uifabric/icons/lib-amd/IconNames.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/IconNames'>;
}
declare module '@uifabric/icons/lib-amd/index.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-amd/index'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-0.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-0'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-1.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-1'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-10.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-10'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-11.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-11'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-12.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-12'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-13.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-13'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-14.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-14'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-2.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-2'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-3.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-3'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-4.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-4'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-5.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-5'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-6.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-6'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-7.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-7'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-8.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-8'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons-9.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons-9'>;
}
declare module '@uifabric/icons/lib-es2015/fabric-icons.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/fabric-icons'>;
}
declare module '@uifabric/icons/lib-es2015/icon-aliases.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/icon-aliases'>;
}
declare module '@uifabric/icons/lib-es2015/IconNames.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/IconNames'>;
}
declare module '@uifabric/icons/lib-es2015/index.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib-es2015/index'>;
}
declare module '@uifabric/icons/lib/fabric-icons-0.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-0'>;
}
declare module '@uifabric/icons/lib/fabric-icons-1.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-1'>;
}
declare module '@uifabric/icons/lib/fabric-icons-10.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-10'>;
}
declare module '@uifabric/icons/lib/fabric-icons-11.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-11'>;
}
declare module '@uifabric/icons/lib/fabric-icons-12.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-12'>;
}
declare module '@uifabric/icons/lib/fabric-icons-13.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-13'>;
}
declare module '@uifabric/icons/lib/fabric-icons-14.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-14'>;
}
declare module '@uifabric/icons/lib/fabric-icons-2.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-2'>;
}
declare module '@uifabric/icons/lib/fabric-icons-3.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-3'>;
}
declare module '@uifabric/icons/lib/fabric-icons-4.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-4'>;
}
declare module '@uifabric/icons/lib/fabric-icons-5.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-5'>;
}
declare module '@uifabric/icons/lib/fabric-icons-6.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-6'>;
}
declare module '@uifabric/icons/lib/fabric-icons-7.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-7'>;
}
declare module '@uifabric/icons/lib/fabric-icons-8.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-8'>;
}
declare module '@uifabric/icons/lib/fabric-icons-9.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons-9'>;
}
declare module '@uifabric/icons/lib/fabric-icons.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/fabric-icons'>;
}
declare module '@uifabric/icons/lib/icon-aliases.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/icon-aliases'>;
}
declare module '@uifabric/icons/lib/IconNames.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/IconNames'>;
}
declare module '@uifabric/icons/lib/index.js' {
  declare module.exports: $Exports<'@uifabric/icons/lib/index'>;
}
