export default {
  ids: [ 772, 776, 778, 779, 780, 781, 783, 788, 789, 790, 791, 792, 793 ],
  entities: {
    '772': {
      lot_site_id: 772,
      lot_site_uid: 10000361,
      lot_site_type_cd: 'P',   
      oper_cntry_cd: 'DEU',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'CopartDE Location',
      addr_line1: 'Test PIV Location',
      addr_line2: 'Test PIV Location Line 2',
      city: 'Calle Aduana',
      state_cd: 'M',
      cntry_cd: 'DEU',
      postal_cd: '28170',
      phone_num: '494691679090',
      alt_phone_num: '49298747292',
      ph_cntry_cd: 'DEU',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '49',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: 'ESW0012543E',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'parna.bolel@copart.com',
      crt_dt: '2016-06-22T21:58:16.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '776': {
      lot_site_id: 776,
      lot_site_uid: 10000363,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'PLANCHA Y PINTURA J. VILLAGRASA',
      addr_line1: 'Isaac Peral,4',
      addr_line2: '',
      city: 'CANOVELLES',
      state_cd: 'B',
      cntry_cd: 'ESP',
      postal_cd: '08420',
      phone_num: '34938400702',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-13T11:25:45.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '778': {
      lot_site_id: 778,
      lot_site_uid: 10000364,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'COMAU S.A.',
      addr_line1: 'AV JUAN CARLOS I 53',
      addr_line2: '',
      city: 'VELEZ-MALAGA',
      state_cd: 'MA',
      cntry_cd: 'ESP',
      postal_cd: '29700',
      phone_num: '34952505200',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-15T08:04:35.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '779': {
      lot_site_id: 779,
      lot_site_uid: 10000365,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'MOTORSOL IMPORT',
      addr_line1: 'URGEL 135',
      addr_line2: '',
      city: 'BARCELONA',
      state_cd: 'B',
      cntry_cd: 'ESP',
      postal_cd: '08015',
      phone_num: '34933239540',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-15T08:19:48.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '780': {
      lot_site_id: 780,
      lot_site_uid: 10000366,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'TALLER PLANCHA CENTRAL',
      addr_line1: 'CALLE DE L\'ENCUNY, 7',
      addr_line2: '',
      city: 'BARCELONA',
      state_cd: 'B',
      cntry_cd: 'ESP',
      postal_cd: '08038',
      phone_num: '34932232211',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-15T08:27:52.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '781': {
      lot_site_id: 781,
      lot_site_uid: 10000367,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'TALLER SANLUCAR MOTOR',
      addr_line1: 'ISAAC PERAL, 28-29 POL. IND. SOLUCA',
      addr_line2: '',
      city: 'SANLUCAR LA MAYOR',
      state_cd: 'SE',
      cntry_cd: 'ESP',
      postal_cd: '41800',
      phone_num: '34955702664',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-15T08:39:31.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '783': {
      lot_site_id: 783,
      lot_site_uid: 10000368,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'AUTOMOVILES PEUGEOT JUAN GINER',
      addr_line1: 'CALLE PERIS Y VALERO, 31',
      addr_line2: '',
      city: 'VALENCIA',
      state_cd: 'V',
      cntry_cd: 'ESP',
      postal_cd: '46006',
      phone_num: '34963343700',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-15T13:27:30.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '788': {
      lot_site_id: 788,
      lot_site_uid: 10000371,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'BUMOTOR',
      addr_line1: 'CALLE DE VITORIA, 291 - KM 4.1',
      addr_line2: '',
      city: 'BURGOS',
      state_cd: 'BU',
      cntry_cd: 'ESP',
      postal_cd: '09007',
      phone_num: '34947482250',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-27T07:58:51.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '789': {
      lot_site_id: 789,
      lot_site_uid: 10000372,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'TALLER HELMANTICA AUDI',
      addr_line1: 'CRTRA, VILLACASTÍN-VIGO,KM 273',
      addr_line2: '',
      city: 'VALCABADO',
      state_cd: 'ZA',
      cntry_cd: 'ESP',
      postal_cd: '49192',
      phone_num: '34980010281',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-27T08:09:07.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '790': {
      lot_site_id: 790,
      lot_site_uid: 10000373,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'TODOMOTO',
      addr_line1: 'AV DE JEREZ , 46',
      addr_line2: '',
      city: 'SEVILLA',
      state_cd: 'SE',
      cntry_cd: 'ESP',
      postal_cd: '41012',
      phone_num: '34954693073',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-27T08:18:41.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '791': {
      lot_site_id: 791,
      lot_site_uid: 10000374,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'TALLER CASTRO MOTOS',
      addr_line1: 'AV. MANUEL FERNANDEZ , MURUBE,42 ( P I Ctra Amarilla )',
      addr_line2: '',
      city: 'SEVILLA',
      state_cd: 'SE',
      cntry_cd: 'ESP',
      postal_cd: '41007',
      phone_num: '34954422255',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-27T08:29:48.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '792': {
      lot_site_id: 792,
      lot_site_uid: 10000375,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'PEUGEOT ZARAGOZA',
      addr_line1: 'AVD DE CATALUÑA,103',
      addr_line2: '',
      city: 'ZARAGOZA',
      state_cd: 'Z',
      cntry_cd: 'ESP',
      postal_cd: '50014',
      phone_num: '34976570068',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-28T06:19:37.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    },
    '793': {
      lot_site_id: 793,
      lot_site_uid: 10000376,
      lot_site_type_cd: 'P',
      oper_cntry_cd: 'ESP',
      vendor_id: null,
      is_commercial_flg: true,
      lot_site_nm: 'AUTOSAE, S.A',
      addr_line1: 'CORMORANES 2-4',
      addr_line2: '',
      city: 'PINTO',
      state_cd: 'M',
      cntry_cd: 'ESP',
      postal_cd: '28320',
      phone_num: '34916928650',
      alt_phone_num: '',
      ph_cntry_cd: 'ESP',
      alt_ph_cntry_cd: null,
      ph_cntry_area_cd: '34',
      alt_ph_cntry_area_cd: null,
      email: 'testpives1@yahoo.com',
      vat_id: '',
      instrn: null,
      biz_hours: null,
      bank_name: '',
      rtng_num: '',
      acct_num: '',
      confirm_rtng_num: '',
      confirm_acct_num: '',
      confirm_iban_acct_num: '',
      iban_acct_num: '',
      bank_cntry_cd: null,
      sync_status: '',
      contact_person: '',
      status: 'A',
      crt_user: 'G2.0 Data Migration',
      crt_dt: '2016-07-28T06:26:28.000Z',
      last_upd_user: 'GCYP-3651',
      last_upd_dt: '2017-12-15T17:17:23.000Z',
      source_sys: 'G1 PH UPD: 12/15/2017',
      source_entry_dt: '2017-10-06T19:40:33.000Z'
    }
  }
}
