// flow-typed signature: 7397074a1987da7707ed6eb8656641fd
// flow-typed version: <<STUB>>/country-telephone-data_v^0.5.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'country-telephone-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'country-telephone-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'country-telephone-data/country_telephone_data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'country-telephone-data/country_telephone_data.js' {
  declare module.exports: $Exports<'country-telephone-data/country_telephone_data'>;
}
