// flow-typed signature: 42d89f6aafb093c431f488c05de76016
// flow-typed version: <<STUB>>/eslint-config-airbnb-easy_v1.0.10

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-airbnb-easy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-airbnb-easy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-airbnb-easy/index' {
  declare module.exports: $Exports<'eslint-config-airbnb-easy'>;
}
declare module 'eslint-config-airbnb-easy/index.js' {
  declare module.exports: $Exports<'eslint-config-airbnb-easy'>;
}
