// flow-typed signature: 13ba860faff4677745f3f687482860f8
// flow-typed version: <<STUB>>/react_v15.6.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react/dist/react-with-addons' {
  declare module.exports: any;
}

declare module 'react/dist/react-with-addons.min' {
  declare module.exports: any;
}

declare module 'react/dist/react' {
  declare module.exports: any;
}

declare module 'react/dist/react.min' {
  declare module.exports: any;
}

declare module 'react/lib/canDefineProperty' {
  declare module.exports: any;
}

declare module 'react/lib/checkReactTypeSpec' {
  declare module.exports: any;
}

declare module 'react/lib/createClass' {
  declare module.exports: any;
}

declare module 'react/lib/deprecated' {
  declare module.exports: any;
}

declare module 'react/lib/flattenChildren' {
  declare module.exports: any;
}

declare module 'react/lib/getIteratorFn' {
  declare module.exports: any;
}

declare module 'react/lib/getNextDebugID' {
  declare module.exports: any;
}

declare module 'react/lib/getNextDebugIDUMDShim' {
  declare module.exports: any;
}

declare module 'react/lib/KeyEscapeUtils' {
  declare module.exports: any;
}

declare module 'react/lib/LinkedStateMixin' {
  declare module.exports: any;
}

declare module 'react/lib/lowPriorityWarning' {
  declare module.exports: any;
}

declare module 'react/lib/onlyChild' {
  declare module.exports: any;
}

declare module 'react/lib/PooledClass' {
  declare module.exports: any;
}

declare module 'react/lib/React' {
  declare module.exports: any;
}

declare module 'react/lib/ReactAddonsDOMDependencies' {
  declare module.exports: any;
}

declare module 'react/lib/ReactAddonsDOMDependenciesUMDShim' {
  declare module.exports: any;
}

declare module 'react/lib/ReactBaseClasses' {
  declare module.exports: any;
}

declare module 'react/lib/ReactChildren' {
  declare module.exports: any;
}

declare module 'react/lib/ReactComponentTreeDevtool' {
  declare module.exports: any;
}

declare module 'react/lib/ReactComponentTreeHook' {
  declare module.exports: any;
}

declare module 'react/lib/ReactComponentTreeHookUMDShim' {
  declare module.exports: any;
}

declare module 'react/lib/ReactComponentWithPureRenderMixin' {
  declare module.exports: any;
}

declare module 'react/lib/ReactCSSTransitionGroup' {
  declare module.exports: any;
}

declare module 'react/lib/ReactCSSTransitionGroupChild' {
  declare module.exports: any;
}

declare module 'react/lib/ReactCurrentOwner' {
  declare module.exports: any;
}

declare module 'react/lib/ReactCurrentOwnerUMDShim' {
  declare module.exports: any;
}

declare module 'react/lib/ReactDOMFactories' {
  declare module.exports: any;
}

declare module 'react/lib/ReactElement' {
  declare module.exports: any;
}

declare module 'react/lib/ReactElementSymbol' {
  declare module.exports: any;
}

declare module 'react/lib/ReactElementType' {
  declare module.exports: any;
}

declare module 'react/lib/ReactElementValidator' {
  declare module.exports: any;
}

declare module 'react/lib/ReactFragment' {
  declare module.exports: any;
}

declare module 'react/lib/ReactLink' {
  declare module.exports: any;
}

declare module 'react/lib/ReactNoopUpdateQueue' {
  declare module.exports: any;
}

declare module 'react/lib/reactProdInvariant' {
  declare module.exports: any;
}

declare module 'react/lib/ReactPropTypeLocationNames' {
  declare module.exports: any;
}

declare module 'react/lib/ReactPropTypeLocations' {
  declare module.exports: any;
}

declare module 'react/lib/ReactPropTypes' {
  declare module.exports: any;
}

declare module 'react/lib/ReactPropTypesSecret' {
  declare module.exports: any;
}

declare module 'react/lib/ReactStateSetters' {
  declare module.exports: any;
}

declare module 'react/lib/ReactTransitionChildMapping' {
  declare module.exports: any;
}

declare module 'react/lib/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'react/lib/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'react/lib/ReactUMDEntry' {
  declare module.exports: any;
}

declare module 'react/lib/ReactUMDShim' {
  declare module.exports: any;
}

declare module 'react/lib/ReactVersion' {
  declare module.exports: any;
}

declare module 'react/lib/ReactWithAddons' {
  declare module.exports: any;
}

declare module 'react/lib/ReactWithAddonsUMDEntry' {
  declare module.exports: any;
}

declare module 'react/lib/shallowCompare' {
  declare module.exports: any;
}

declare module 'react/lib/sliceChildren' {
  declare module.exports: any;
}

declare module 'react/lib/traverseAllChildren' {
  declare module.exports: any;
}

declare module 'react/lib/update' {
  declare module.exports: any;
}

declare module 'react/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react/dist/react-with-addons.js' {
  declare module.exports: $Exports<'react/dist/react-with-addons'>;
}
declare module 'react/dist/react-with-addons.min.js' {
  declare module.exports: $Exports<'react/dist/react-with-addons.min'>;
}
declare module 'react/dist/react.js' {
  declare module.exports: $Exports<'react/dist/react'>;
}
declare module 'react/dist/react.min.js' {
  declare module.exports: $Exports<'react/dist/react.min'>;
}
declare module 'react/lib/canDefineProperty.js' {
  declare module.exports: $Exports<'react/lib/canDefineProperty'>;
}
declare module 'react/lib/checkReactTypeSpec.js' {
  declare module.exports: $Exports<'react/lib/checkReactTypeSpec'>;
}
declare module 'react/lib/createClass.js' {
  declare module.exports: $Exports<'react/lib/createClass'>;
}
declare module 'react/lib/deprecated.js' {
  declare module.exports: $Exports<'react/lib/deprecated'>;
}
declare module 'react/lib/flattenChildren.js' {
  declare module.exports: $Exports<'react/lib/flattenChildren'>;
}
declare module 'react/lib/getIteratorFn.js' {
  declare module.exports: $Exports<'react/lib/getIteratorFn'>;
}
declare module 'react/lib/getNextDebugID.js' {
  declare module.exports: $Exports<'react/lib/getNextDebugID'>;
}
declare module 'react/lib/getNextDebugIDUMDShim.js' {
  declare module.exports: $Exports<'react/lib/getNextDebugIDUMDShim'>;
}
declare module 'react/lib/KeyEscapeUtils.js' {
  declare module.exports: $Exports<'react/lib/KeyEscapeUtils'>;
}
declare module 'react/lib/LinkedStateMixin.js' {
  declare module.exports: $Exports<'react/lib/LinkedStateMixin'>;
}
declare module 'react/lib/lowPriorityWarning.js' {
  declare module.exports: $Exports<'react/lib/lowPriorityWarning'>;
}
declare module 'react/lib/onlyChild.js' {
  declare module.exports: $Exports<'react/lib/onlyChild'>;
}
declare module 'react/lib/PooledClass.js' {
  declare module.exports: $Exports<'react/lib/PooledClass'>;
}
declare module 'react/lib/React.js' {
  declare module.exports: $Exports<'react/lib/React'>;
}
declare module 'react/lib/ReactAddonsDOMDependencies.js' {
  declare module.exports: $Exports<'react/lib/ReactAddonsDOMDependencies'>;
}
declare module 'react/lib/ReactAddonsDOMDependenciesUMDShim.js' {
  declare module.exports: $Exports<'react/lib/ReactAddonsDOMDependenciesUMDShim'>;
}
declare module 'react/lib/ReactBaseClasses.js' {
  declare module.exports: $Exports<'react/lib/ReactBaseClasses'>;
}
declare module 'react/lib/ReactChildren.js' {
  declare module.exports: $Exports<'react/lib/ReactChildren'>;
}
declare module 'react/lib/ReactComponentTreeDevtool.js' {
  declare module.exports: $Exports<'react/lib/ReactComponentTreeDevtool'>;
}
declare module 'react/lib/ReactComponentTreeHook.js' {
  declare module.exports: $Exports<'react/lib/ReactComponentTreeHook'>;
}
declare module 'react/lib/ReactComponentTreeHookUMDShim.js' {
  declare module.exports: $Exports<'react/lib/ReactComponentTreeHookUMDShim'>;
}
declare module 'react/lib/ReactComponentWithPureRenderMixin.js' {
  declare module.exports: $Exports<'react/lib/ReactComponentWithPureRenderMixin'>;
}
declare module 'react/lib/ReactCSSTransitionGroup.js' {
  declare module.exports: $Exports<'react/lib/ReactCSSTransitionGroup'>;
}
declare module 'react/lib/ReactCSSTransitionGroupChild.js' {
  declare module.exports: $Exports<'react/lib/ReactCSSTransitionGroupChild'>;
}
declare module 'react/lib/ReactCurrentOwner.js' {
  declare module.exports: $Exports<'react/lib/ReactCurrentOwner'>;
}
declare module 'react/lib/ReactCurrentOwnerUMDShim.js' {
  declare module.exports: $Exports<'react/lib/ReactCurrentOwnerUMDShim'>;
}
declare module 'react/lib/ReactDOMFactories.js' {
  declare module.exports: $Exports<'react/lib/ReactDOMFactories'>;
}
declare module 'react/lib/ReactElement.js' {
  declare module.exports: $Exports<'react/lib/ReactElement'>;
}
declare module 'react/lib/ReactElementSymbol.js' {
  declare module.exports: $Exports<'react/lib/ReactElementSymbol'>;
}
declare module 'react/lib/ReactElementType.js' {
  declare module.exports: $Exports<'react/lib/ReactElementType'>;
}
declare module 'react/lib/ReactElementValidator.js' {
  declare module.exports: $Exports<'react/lib/ReactElementValidator'>;
}
declare module 'react/lib/ReactFragment.js' {
  declare module.exports: $Exports<'react/lib/ReactFragment'>;
}
declare module 'react/lib/ReactLink.js' {
  declare module.exports: $Exports<'react/lib/ReactLink'>;
}
declare module 'react/lib/ReactNoopUpdateQueue.js' {
  declare module.exports: $Exports<'react/lib/ReactNoopUpdateQueue'>;
}
declare module 'react/lib/reactProdInvariant.js' {
  declare module.exports: $Exports<'react/lib/reactProdInvariant'>;
}
declare module 'react/lib/ReactPropTypeLocationNames.js' {
  declare module.exports: $Exports<'react/lib/ReactPropTypeLocationNames'>;
}
declare module 'react/lib/ReactPropTypeLocations.js' {
  declare module.exports: $Exports<'react/lib/ReactPropTypeLocations'>;
}
declare module 'react/lib/ReactPropTypes.js' {
  declare module.exports: $Exports<'react/lib/ReactPropTypes'>;
}
declare module 'react/lib/ReactPropTypesSecret.js' {
  declare module.exports: $Exports<'react/lib/ReactPropTypesSecret'>;
}
declare module 'react/lib/ReactStateSetters.js' {
  declare module.exports: $Exports<'react/lib/ReactStateSetters'>;
}
declare module 'react/lib/ReactTransitionChildMapping.js' {
  declare module.exports: $Exports<'react/lib/ReactTransitionChildMapping'>;
}
declare module 'react/lib/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'react/lib/ReactTransitionEvents'>;
}
declare module 'react/lib/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'react/lib/ReactTransitionGroup'>;
}
declare module 'react/lib/ReactUMDEntry.js' {
  declare module.exports: $Exports<'react/lib/ReactUMDEntry'>;
}
declare module 'react/lib/ReactUMDShim.js' {
  declare module.exports: $Exports<'react/lib/ReactUMDShim'>;
}
declare module 'react/lib/ReactVersion.js' {
  declare module.exports: $Exports<'react/lib/ReactVersion'>;
}
declare module 'react/lib/ReactWithAddons.js' {
  declare module.exports: $Exports<'react/lib/ReactWithAddons'>;
}
declare module 'react/lib/ReactWithAddonsUMDEntry.js' {
  declare module.exports: $Exports<'react/lib/ReactWithAddonsUMDEntry'>;
}
declare module 'react/lib/shallowCompare.js' {
  declare module.exports: $Exports<'react/lib/shallowCompare'>;
}
declare module 'react/lib/sliceChildren.js' {
  declare module.exports: $Exports<'react/lib/sliceChildren'>;
}
declare module 'react/lib/traverseAllChildren.js' {
  declare module.exports: $Exports<'react/lib/traverseAllChildren'>;
}
declare module 'react/lib/update.js' {
  declare module.exports: $Exports<'react/lib/update'>;
}
declare module 'react/react.js' {
  declare module.exports: $Exports<'react/react'>;
}
