// flow-typed signature: 7f856ffa57dc7ae37e1753486fe41b42
// flow-typed version: <<STUB>>/react-with-context_v1.2.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-context/bin/WithContext' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-context/bin/WithContext.js' {
  declare module.exports: $Exports<'react-with-context/bin/WithContext'>;
}
